# Functions
fastfetch-run() {
    local script_path="${ZSH}/RandomFastfetchIcon.sh"

    if [[ "$TERM_PROGRAM" != "konsole" && -z "$KONSOLE_VERSION" ]]; then
        if [[ -x "$script_path" ]]; then
            "$script_path"
        else
            logger -t "fastfetch-run" -p user.err "Ошибка: Файл скрипта не найден или не является исполняемым по пути: $script_path"
        fi
    fi
}

clear-on-empty() {
    if [[ -z "$BUFFER" ]]; then
        zle clear-screen
    else
        zle accept-line
    fi
}

clear-and-show-fastfetch() {
    if [[ -z "$BUFFER" ]]; then
        fastfetch-run
        zle accept-line
    else
        zle accept-line
    fi
}

# Export
export ZSH="$HOME/.oh-my-zsh"
export EDITOR="code"

ZSH_THEME="eandset/agnosterzakpink"

plugins=(
    git
    # archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
)

eval "$(zoxide init zsh)"

source $ZSH/oh-my-zsh.sh

# Start
fastfetch-run

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Set-up icons for files/directories in terminal using lsd
# alias ls='lsd'
# alias l='ls -l'
# alias la='ls -a'
# alias lla='ls -la'
# alias lt='ls --tree'

# Simpler
# alias cd="z"

# Binds
# source <(fzf --zsh) # Set-up FZF key bindings (CTRL R for fuzzy history finder)

zle -N clear-and-show-fastfetch
bindkey '^N' clear-and-show-fastfetch

zle -N clear-on-empty
bindkey '^M' clear-on-empty
